# Generated by Django 4.2 on 2024-09-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_slug_project_slug_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
